language: node_js
git:
  depth: false

dist: trusty
sudo: required

branches:
  only:
    - master

matrix:
  include:
    - node_js: 8
      env: TEST_SUITE=unit
      install:
        - npm i
        - npm i -g codecov
      script:
        - npm run test:unit-ci
      after_success:
        - codecov

    - node_js: 8
      env: TEST_SUITE=lint
      install: npm i
      script: npm run lint

    - node_js: 8
      services:
        - docker
      env:
        - TEST_SUITE=screenshots
        - CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
      before_install:
        - docker build -t screenshots .
        - docker image ls
      script:
        - docker run -it --rm --cap-add=SYS_ADMIN -e MDC_GCLOUD_SERVICE_ACCOUNT_KEY="${MDC_GCLOUD_SERVICE_ACCOUNT_KEY}" screenshots /bin/sh -c "git checkout '${CURRENT_BRANCH}'; /home/pptruser/material-components-web-react/test/screenshot/start.sh; sleep 200s; npm run test:image-diff"
